apiVersion: v1
kind: Pod
metadata:
  name: task-04
spec:
  securityContext:
    fsGroup: 3000
  containers:
  - name: container-01
    image: custom-image-name:version
    securityContext:
      runAsUser: 1000
      allowPrivilegeEscalation: false
  - name: container-02
    image: custom-image-name:version
    securityContext:
      runAsUser: 2000
      allowPrivilegeEscalation: false